//Create the following classes
//Employee
   //Prop	
	//string Name -> no blanks
	//int EmpNo -> readonly, autogenerated
	//short DeptNo -> > 0

  //  abstract decimal Basic
  // Methods
    //abstract decimal CalcNetSalary()


//Manager: Employee
 // Prop

   // string Designation -> cant be blank
	

//GeneralManager : Manager
  // Prop
 	//string Perks -> no validations

//CEO : Employee
      //Make CalNetSalary() a sealed method

//NOTE : Overloaded constructors in all classes calling their base class constructor
//All classes must implement IDbFunctions interface
//All classes to override the abstract members defined in the base class(Employee).Basic property to have different validation in different classes.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assign3_1
{
    class Program
    {
        static void Main()
        {

            Console.WriteLine("Details");
            Console.WriteLine("Manager");
            Manager m = new Manager("tejaswini", 2, 50000, "Manager");
            Console.WriteLine("Employee ID : " + " " + m.EMPNO);
            Console.WriteLine("Name : " + " " + m.NAME);
            Console.WriteLine("Dept no : " + " " + m.DEPTNO);
            Console.WriteLine("Net salary : " + " " + m.CalcNetSalary());
            Console.WriteLine("Designation : " + " " + m.DESIGNATION);
            m.Insert();
            m.Upadte();
            m.Delete();

            Console.WriteLine(" ");
            Console.WriteLine("General Manager");
            GeneralManager g = new GeneralManager("teju", 3, 60000, "General Manager", "perk1");
            Console.WriteLine("Employee ID : " + " " + g.EMPNO);
            Console.WriteLine("Name : " + " " + g.NAME);
            Console.WriteLine("Dept no : " + " " + g.DEPTNO);
            Console.WriteLine("Net Salary : " + " " + g.CalcNetSalary());
            Console.WriteLine("Designation : " + " " + g.DESIGNATION);
            g.Insert();
            g.Upadte();
            g.Delete();

            Console.WriteLine(" ");
            Console.WriteLine("CEO");
            CEO c = new CEO("tej", 4, 70000);
            Console.WriteLine("Employee ID : " + " " + c.EMPNO);
            Console.WriteLine("Name : " + " " + c.NAME);
            Console.WriteLine("Dept no : " + " " + c.DEPTNO);
            Console.WriteLine("Net salary : " + " " + c.CalcNetSalary());
            c.Insert();
            c.Upadte();
            c.Delete();

            Console.ReadLine();






        }
    }

    public interface IDbFunctions
    {
        void Insert();
        void Upadte();
        void Delete();

    }




    public abstract class Employee : IDbFunctions
    {
        private String Name;
        private readonly int Empno;
        private short DeptNo;
        protected decimal Basic;
        private static int counter = 1;
        public abstract decimal CalcNetSalary();

        public void Insert()
        {
            Console.WriteLine("Employee insert");
        }

        public void Upadte()
        {
            Console.WriteLine("Employee Update");
        }

        public void Delete()
        {
            Console.WriteLine("Employee Delete");
        }

        #region Properties
        public String NAME
        {
            set
            {
                if (value != " ")
                {
                    Name = value;
                }
            }

            get
            {
                return Name;

            }
        }

        public int EMPNO
        {

            get
            {
                return Empno;
            }

        }

        public short DEPTNO
        {
            set
            {
                if (value > 0)
                {
                    DeptNo = value;
                }

            }
            get { return DeptNo; }

        }

        public abstract decimal BASIC
        {
            set;
            get;

        }

        public Employee(string Name = "Employee default", short DeptNo = 1, decimal Basic = 50000)
        {
            this.NAME = Name;
            this.DEPTNO = DeptNo;
            this.BASIC = Basic;

            Empno = counter++;
        }



        #endregion


    }


    public class Manager : Employee
    {
        public override decimal BASIC
        {
            get;
            set;
        }
        private String Designation;

        #region Properties Manager
        public String DESIGNATION
        {
            set
            {
                if (value != " ")
                {
                    Designation = value;
                }
            }

            get
            {
                return Designation;
            }
        }

        #endregion


        public new void Insert()
        {
            Console.WriteLine("Manager Insert");
        }

        public new void Upadte()
        {
            Console.WriteLine("Mnagaer Upate");
        }

        public new void Delete()
        {
            Console.WriteLine("Manager Delete");
        }

        public override decimal CalcNetSalary()
        {
            decimal Netsalary = BASIC + (BASIC / 4);
            return Netsalary;
        }

        public Manager(string Name = "Employee default", short DeptNo = 2, decimal Basic = 60000, String Designation = "Manager") : base(Name, DeptNo, Basic)
        {
            this.NAME = Name;
            this.DEPTNO = DeptNo;
            this.BASIC = Basic;
            this.DESIGNATION = Designation;

        }


    }


    public class GeneralManager : Manager
    {
        private string Perks;

        public string PERKS
        {
            set;
            get;

        }

        public GeneralManager(string Name = "Employee default", short DeptNo = 3, decimal Basic = 70000, String Designation = "General Manager", String Perks = "Perks") : base(Name, DeptNo, Basic, Designation)
        {
            this.NAME = Name;
            this.DEPTNO = DeptNo;
            this.BASIC = Basic;
            this.DESIGNATION = Designation;
            this.PERKS = Perks;


        }

        public new void Insert()
        {
            Console.WriteLine("General Manager Insert");
        }

        public new void Upadte()
        {
            Console.WriteLine("General Mnagaer Upate");
        }

        public new void Delete()
        {
            Console.WriteLine("General Manager Delete");
        }


    }


    public class CEO : Employee
    {
        public override decimal BASIC
        {
            get;
            set;
        }

        public CEO(string Name = "Employee default", short DeptNo = 4, decimal Basic = 80000) : base(Name, DeptNo, Basic)
        {
            this.NAME = Name;
            this.DEPTNO = DeptNo;
            this.BASIC = Basic;


        }


        public override sealed decimal CalcNetSalary()
        {
            decimal Netsalary = BASIC + (BASIC / 4);
            return Netsalary;
        }

        public new void Insert()
        {
            Console.WriteLine("CEO Insert");
        }

        public new void Upadte()
        {
            Console.WriteLine("CEO Upate");
        }

        public new void Delete()
        {
            Console.WriteLine("CEO Delete");
        }




    }
}